name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-latest]
        build_type: [Debug, Release]
        compiler: [gcc g++, clang clang++]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install libopenblas-dev libarmadillo-dev libyaml-cpp-dev
            
    - name: Make build dir
      run: mkdir build 
    
    - name: Make install dir
      run: mkdir install
    
    - name: Configure
      run: > 
          export CC=$(echo  "${{ matrix.compiler }}" | cut -d' ' -f1) && 
          export CXX=$(echo "${{ matrix.compiler }}" | cut -d' ' -f2) && 
          cd build && cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DENABLE_TESTING:BOOL=FALSE -DCMAKE_INSTALL_PREFIX=../install ..

    - name: Build
      run: cd build && cmake .. && make install
   
    - name: Cleanall examples
      working-directory: ./tests
      run: ./cleanall.sh

    - name: Test
      working-directory: ./tests
      run: ./runall.sh
    # run: >
    #     export KAPPA_DIRECTORY=$(pwd) &&
    #     export KAPPA_DATA_DIRECTORY=$KAPPA_DIRECTORY/data &&
    #     export LD_LIBRARY_PATH=$KAPPA_DIRECTORY/install/lib:$LD_LIBRARY_PATH &&
    #     cd build && ctest
